### ISSUE TITLE
Cannot control border radius of comment css style

### ISSUE THREAD

**Issue by Zxynine** [Zxynine/EvenBetterComments#8]
@Fred-Vatin
"Could you add a property to custom border-radius ? 😅"

@Zxynine 
"As for the border radius, it’s weird that you cannot set that with the css border options, I’ve always hated css with a passion. I’m currently working on a way to let users specify every css option without me specifically adding support for each one."

Adding in full support for Css styling options for advanced users.

**Comment by Zxynine** [comment]
@Fred-Vatin
All issues with the tag "possibly fixed" should be fixed in this new update I just pushed.
I have immedietly depricated `tag.CSSBorderDecoration`, `tag.CSSOutlineDecoration`, `tag.CSSTextDecoration`
So they now do nothing, in their place I have implemented `tag.CustomDecoration` which overrides all styling options for the tag (meaning if you use it you need to set colour, bold, underline, etc in `tag.CustomDecoration`). It will be converted directly into vscodes [DecorationRenderOptions object](https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions) so you use the exact property names and options to set your tag how you wish. I added in extensive code hints when you are typing the settings so it should help you a fair bit.

Let me know if the issues are all fixed. If they arent I will reopen the problematic issues.

**Comment by Fred-Vatin** [comment]
It seems as expected. Nice job !
![image](https://user-images.githubusercontent.com/22337329/208761846-fd9a9079-4f63-4f4d-8ff1-c79b4d48d815.png)
